---
title: Using R for Statistical Analysis of Survey Data 
author: javaria 
date: 20 Dec 2020 
output: html_document
---

# Intro

R is a natural place to play with data and collections of natural / artificial data recorders, commonly in the form of electronic devices, ranging fromm cell phones to embedded platforms.


```{r} 

set.seed(786)
DF<-read.csv('input.csv',sep=';')
print('Found columns:')
print(colnames(DF))



```

```{r} 
#DF$Age
#DF$Age<-as.integer(as.factor(DF$Age))
#DF$Age<-scale(DF$Age)

#for (col in colnames(DF)){
#print('Doing')
#print(col)
#DF[col]<-as.integer(as.factor(DF[col]))
#DF[col]<-scale(DF[col])
#}
```
```{r} 
for (col in 1:ncol(DF)){
#print('Doing')
#print(col)
DF[,col]<-as.integer(as.factor(DF[,col]))
DF[,col]<-scale(DF[,col])
}
#str(DF)
dist_matrix=dist(DF,method='euclidean')
hclust_avg=hclust(dist_matrix,method='average')
plot(hclust_avg)
```
```{r} 
#cut_avg=cutree(hclust_avg,k=3)
#rect.hclust(hclust_avg,k=3,border=2:6)
#abline(h=3,col='red')
```
```{r} 
#avg_dend_obj=as.dendrogram(hclust_avg)
#suppressPackageStartupMessages(library(dendextend))
#avg_col_dend=color_branches(avg_dend_obj,h=3)
#plot(avg_col_dend)




```








